### ISSUE TITLE
自動デプロイ用のWorkflowを組む

### ISSUE THREAD

**Issue by YumNumm** [YumNumm/ticket-system#8]
## 概要
- 現在、Cloudflare Pagesにデプロイしている
  - 自動でデプロイするGitHub Actions Workflowを組みたい

## メモ
- 外部リポジトリへの依存はないためSSH Keyのセットアップは不要
- タイムアウトは10分にすること
- ブランチはmainのみ自動実行 
  - 手動実行できるようにすること
- Cloudflare Pagesのproject-idは`ticket-system`です

## 参考
```yaml
name: Deploy Web (Main)
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_ID_ED25519 }}" | base64 -d > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          echo "Host github.com \n\tIdentityFile ~/.ssh/id_ed25519\n\tUser git\n\tIdentityiesOnly yes" >> ~/.ssh/config
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Setup melos
        run: |
          ln -s $FLUTTER_ROOT .fvm/flutter_sdk
          dart pub global activate melos
          melos bootstrap

      - name: build_runner
        run: |
          echo '${{ secrets.ENV }}' | base64 -d > app/.env
          melos generate

      - name: Build web
        working-directory: app
        run: flutter build web --release --wasm

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 4270d8a14dfc1f866629099a788c93e2
          projectName: eqmonitor-web
          directory: app/build/web
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          wranglerVersion: "3"
```
